if(NOT Core_FOUND)
  if(BLAZE_INSTALL)
    set(SOURCEMETA_CORE_INSTALL ON CACHE BOOL "enable installation")
  else()
    set(SOURCEMETA_CORE_INSTALL OFF CACHE BOOL "disable installation")
  endif()

  set(SOURCEMETA_CORE_EXTENSION_BUILD OFF CACHE BOOL "disable")

  set(SOURCEMETA_CORE_ADDRESS_SANITIZER ${BLAZE_ADDRESS_SANITIZER}
    CACHE BOOL "address sanitizer")
  set(SOURCEMETA_CORE_UNDEFINED_SANITIZER ${BLAZE_UNDEFINED_SANITIZER}
    CACHE BOOL "undefined behavior sanitizer")

  set(SOURCEMETA_CORE_CONTRIB_GOOGLETEST ${BLAZE_TESTS} CACHE BOOL "GoogleTest")
  set(SOURCEMETA_CORE_CONTRIB_GOOGLEBENCHMARK ${BLAZE_BENCHMARK} CACHE BOOL "GoogleBenchmark")
  add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/core")
  include(Sourcemeta)
  set(Core_FOUND ON)
endif()
