if(NOT Core_FOUND)
  set(SOURCEMETA_CORE_REGEX OFF CACHE BOOL "disable regex support")
  set(SOURCEMETA_CORE_URI OFF CACHE BOOL "disable URI support")
  set(SOURCEMETA_CORE_JSONSCHEMA OFF CACHE BOOL "disable JSON Schema support")
  set(SOURCEMETA_CORE_JSONPOINTER OFF CACHE BOOL "disable JSON Pointer support")
  set(SOURCEMETA_CORE_JSONL OFF CACHE BOOL "disable JSONL support")
  set(SOURCEMETA_CORE_EXTENSION_ALTERSCHEMA OFF CACHE BOOL "disable AlterSchema support")
  set(SOURCEMETA_CORE_YAML OFF CACHE BOOL "disable YAML support")
  set(SOURCEMETA_CORE_CONTRIB_GOOGLETEST OFF CACHE BOOL "GoogleTest")
  set(SOURCEMETA_CORE_CONTRIB_GOOGLEBENCHMARK OFF CACHE BOOL "GoogleBenchmark")
  add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/core")
  include(Sourcemeta)
  set(Core_FOUND ON)
endif()
